term.setBackgroundColor(2048)
term.clear()
term.setCursorPos(1,1)
textutils.slowPrint("Doggy OS Has shutdown to prevent damage or protect data")
textutils.slowPrint("Collecting Data...")
textutils.slowPrint("We will Restart your device soon...")
term.setBackgroundColor(2048)
sleep(5)
os.reboot()
