term.clear()
term.setCursorPos(1,1)
print("Loading VA11-ILLA")
sleep(2)
term.clear()
term.setCursorPos(1,1)
print("Welcome to VA11-ILLA")
print("--------------------------")
print("VA11-ILLA version: 12.0")
print("Doggy OS version: Standard 12.0")
print("Desktop: Yes")
print("Bootloader: Offical")
print("Root access: Enabled")
print("Security: Doggy OS enterprise security 3.0")
read()
shell.run("/disk/os/gui")

