term.clear()
term.setCursorPos(1,1)
print("Fixing boot sector")
print("Do NOT remove SSD/HDD from device")
sleep(5)
term.clear()
term.setCursorPos(1,1)
print("This will Wipe your old bootloader!, press enter to confirm")
read()
print("Clearing old boot sector")
sleep(2)
shell.run("delete","/no-os")
shell.run("delete","/startup")
sleep(2)
term.clear()
term.setCursorPos(1,1)
textutils.slowPrint("-----------------------------")
term.clear()
term.setCursorPos(1,1)
shell.run("cp","/disk/boot/error/","/startup")
shell.run("cp","/disk/bootloader/no-os.lua","/no-os")
print("Bootloader repaired")
sleep(3)
os.reboot()
