term.clear()
term.setCursorPos(1,1)
shell.run("delete","/disk2/disk")
shell.run("cp","/disk/os/menu.lua","menu")
shell.run("cp","/disk/","/disk2/")
shell.run("cp","/disk/","/disk2/recovery")
shell.run("cp","/disk/pocket/start","/disk2/startup")
sleep(3)
term.clear()
print("VA11-ILLA Recovery Completed")
read()
shell.run("/disk/os/home")
